name: MainMCPlugin
version: '${project.version}'
main: com.evangreener.mainmcplugin.MainMCPlugin
api-version: 1.16
authors: [ EvanGreener ]
description: The main server plugin for my mc server
commands:
  cmds:
    usage: /cmds | /cmds help
    description: List server specific commands

  tp-spawn:
    usage: /tp-spawn
    description: Teleport to world spawn
